// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd1HEdvyejmjE1JWHtmXy95axOcvZ3z24',
    appId: '1:411580198161:web:8d85ddbaa8ffeb795df0b0',
    messagingSenderId: '411580198161',
    projectId: 'paypoint-a2569',
    authDomain: 'paypoint-a2569.firebaseapp.com',
    storageBucket: 'paypoint-a2569.firebasestorage.app',
    measurementId: 'G-D9HNHGMPN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhY0HX7Bb4MOscOLfA0lFQl1dFXn4PaZg',
    appId: '1:411580198161:android:dd8fbfbae9982f365df0b0',
    messagingSenderId: '411580198161',
    projectId: 'paypoint-a2569',
    storageBucket: 'paypoint-a2569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVXKBwjYlQ_FrMQmMQAlELep81QtMesY',
    appId: '1:411580198161:ios:0696576af61e103e5df0b0',
    messagingSenderId: '411580198161',
    projectId: 'paypoint-a2569',
    storageBucket: 'paypoint-a2569.firebasestorage.app',
    iosBundleId: 'com.example.paypoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIVXKBwjYlQ_FrMQmMQAlELep81QtMesY',
    appId: '1:411580198161:ios:0696576af61e103e5df0b0',
    messagingSenderId: '411580198161',
    projectId: 'paypoint-a2569',
    storageBucket: 'paypoint-a2569.firebasestorage.app',
    iosBundleId: 'com.example.paypoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd1HEdvyejmjE1JWHtmXy95axOcvZ3z24',
    appId: '1:411580198161:web:30a47402130068f45df0b0',
    messagingSenderId: '411580198161',
    projectId: 'paypoint-a2569',
    authDomain: 'paypoint-a2569.firebaseapp.com',
    storageBucket: 'paypoint-a2569.firebasestorage.app',
    measurementId: 'G-E6BGK9LPD1',
  );
}
